[build]
# Build in release mode
release = false
# The public URL from which assets are to be served.
public_url = "/"

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = true

[watch]
# Paths to ignore when watching for changes
ignore = ["target"] 